### ISSUE TITLE
Check for interupts in C++ code

### ISSUE THREAD

**Issue by gergness** [mnpopcenter/ripums#19]
I have no experience with this, but can be annoying when loading large files. The readr portion is interuptable, but for hierarchical files my C++ code isn't.

http://gallery.rcpp.org/articles/using-rcppprogress/

That post is old, I think check for user interupt is built into Rcpp now (https://github.com/tidyverse/dplyr/blob/d6b4eac2c40e2db23094347ecfb8c6babb4c1e8e/src/summarise.cpp#L125)

**Comment by mpadge** [comment]
apologies @gergness for my complete lack of involvement to date - you've done some great work in the meantime! I **will** find time to do some C++ magic very soon! On this issue, however, I'm sure you'll do just as good a job - `Rcpp::checkUserInterrupt()`  is explained really well in the [attributes vignette](https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-attributes.pdf).

**Comment by gergness** [comment]
Awesome, thanks for the pointers! I thought it might be more complicated.
