### ISSUE TITLE
add pkgdown docs

### ISSUE THREAD

**Issue by mpadge** [mnpopcenter/ripums#20]
[`pkgdown`](https://github.com/r-lib/pkgdown) can be used to generate static docs for the `ipumsr.github.io` website. You can then put the link at the top of the repo, and people can go straight to a nicely formatted website. It's all pretty automatic, you just need to create/copy a nice `_pkgdown.yml` (example [here](https://github.com/ropensci/bikedata/blob/master/_pkgdown.yml)), run `pkgdown::build_site()`, and put the url at top of the repo. Probably more fun for you to do yourself than for me to do it as a PR!

**Comment by gergness** [comment]
Yeah, I've been meaning to try pkgdown out for srvyr. 

I'll keep it in mind for ipumsr, too, but am closing for now. I suspect this would create a lot of concern about how the pkgdown website fits in with our main website, whether we could host it there and how closely the designs can match (and I've already ruffled a few feathers on similar issues, so I want to lay low).

**Comment by mpadge** [comment]
Yeah, totally fair enough.
