### ISSUE TITLE
"Big Data"

### ISSUE THREAD

**Issue by gergness** [mnpopcenter/ripums#5]
Provide guidance to users who can't fit all data into memory.

I see 2 ways forward:
- Vignette describing how to use other packages to solve this problem (Databases, Spark, LaF package, others)

- Option in functions to send to one or more of these structures

Also need more research into pros and cons of each

**Comment by gergness** [comment]
https://community.rstudio.com/t/best-practice-to-handle-out-of-memory-data/734

**Comment by nalsalam** [comment]
I am running into the "cannot allocate vector of size ... " problem.  It would be helpful if read_ipums_micro() provided a means of filtering.  The CPS extracts include all ages, for example, but my analysis only requires a narrow range of ages.

**Comment by joegrover** [comment]
@nalsalam You can actually filter your data extract via the IPUMS web interface by using [Select Cases](https://cps.ipums.org/cps-action/faq#ques33) option in the extract menu. You can modify your current extract by clicking the "revise" from your ['My Data'](https://cps.ipums.org/cps-action/extract_requests/download) page and then clicking the "Select Cases" button.
