### ISSUE TITLE
Error in `read_ipums_ddi`

### ISSUE THREAD

**Issue by chengchou** [mnpopcenter/ripums#61]
I updated my R and `ipumsr` package recently. I got the following error from `read_ipums_ddi`. The same program was ran successfully in May 2019. I tried to install `ipumsr` 0.3.0 and 0.4.0, but neither helps fix the issue. From the traceback, I suspect that it may be caused by the update of `vctrs` package.

```
> ddi <- read_ipums_ddi("MTUS2/mtus_00002.xml")
Error: Can't combine `..1$val` <character> and `..2$val` <double>.
```

Here is traceback:
```
> rlang::last_error()
<error/vctrs_error_incompatible_type>
Can't combine `..1$val` <character> and `..2$val` <double>.
Backtrace:
  1. ipumsr::read_ipums_ddi("MTUS2/mtus_00002.xml")
  7. vctrs::vec_default_ptype2(...)
  8. vctrs::stop_incompatible_type(...)
  9. vctrs:::stop_incompatible(...)
 10. vctrs:::stop_vctrs(...)
Run `rlang::last_trace()` to see the full context.
```

Here is my session info:
```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ipumsr_0.3.0   devtools_2.3.0 usethis_1.6.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6      compiler_4.0.0    pillar_1.4.4      forcats_0.5.0     prettyunits_1.1.1
 [6] remotes_2.1.1     tools_4.0.0       zeallot_0.1.0     testthat_2.3.2    digest_0.6.25    
[11] packrat_0.5.0     pkgbuild_1.0.8    pkgload_1.1.0     memoise_1.1.0     lifecycle_0.2.0  
[16] tibble_3.0.1      pkgconfig_2.0.3   rlang_0.4.6       cli_2.0.2         rstudioapi_0.11  
[21] haven_2.3.1       xml2_1.3.2        stringr_1.4.0     withr_2.2.0       dplyr_1.0.0      
[26] hms_0.5.3         desc_1.2.0        generics_0.0.2    fs_1.4.1          vctrs_0.3.0      
[31] rprojroot_1.3-2   tidyselect_1.1.0  glue_1.4.1        R6_2.4.1          processx_3.4.2   
[36] fansi_0.4.1       sessioninfo_1.1.1 callr_3.4.3       purrr_0.3.4       magrittr_1.5     
[41] backports_1.1.7   ps_1.3.3          ellipsis_0.3.1    assertthat_0.2.1  stringi_1.4.6    
[46] crayon_1.3.4    
```

**Comment by dtburk** [comment]
Thanks for filing this issue @chengchou . Could you email the .xml file you are trying to load to ipums+cran@umn.edu? I suspect you may be right about the origin of the problem, but having the DDI file will help us debug the issue more quickly.

**Comment by chengchou** [comment]
Thanks @dtburk. I have just emailed the DDI file. I also posted the DDI file as a public gist, in case other users may also want to understand the issue.

Here is the link to DDI file on
https://gist.github.com/chengchou/4c1b41a85979ea8e8376da279e9d68f9

**Comment by chengchou** [comment]
@dtburk I think I have fixed this issue. The problem was caused by line 241 of the file `ddi_read.r`, which is copied below.

```
      out <- dplyr::bind_rows(lbls, extra_labels)
```

When `extra_labels` is empty, its `val` column is of type double regardless of the value type of the `val` column in `lbls`. Here is the example from my DDI file.

```
>       lbls
# A tibble: 57 x 2
   val    lbl                
   <chr>  <chr>              
 1 UK2014 United Kingdom 2014
 2 NL1990 Netherlands 1990   
 3 NL1985 Netherlands 1985   
 4 NL1980 Netherlands 1980   
 5 NL1975 Netherlands 1975   
 6 ES2009 Spain 2009         
 7 ES2002 Spain 2002         
 8 US2012 United States 2012 
 9 US2011 United States 2011 
10 US2010 United States 2010 
# … with 47 more rows
>       extra_labels
# A tibble: 0 x 2
# … with 2 variables: val <dbl>, lbl <chr>
```

When we use `bind_rows` to combine `lbls` and `extra_labels`, it got the issue of incompatible types (`chr` and `dbl`). This explains the error message `Error: Can't combine `..1$val` <character> and `..2$val` <double>.` My fix is naive, I just add an if condition like below to avoid using `bind_rows` unless `extra_labels` is nonempty. It works for me now. Please advise me if this has side effect.

```
      if (nrow(extra_labels) > 0) {
        out <- dplyr::bind_rows(lbls, extra_labels)
      } else {
        out <- lbls
      }
```

**Comment by dtburk** [comment]
Thanks very much for sharing the DDI file and finding the source of the problem, @chengchou! Your solution would work perfectly as far as I can tell, but I opted to make the fix one step earlier, by making sure that the `val` column is set to the correct type even when `extra_labels` is empty.

**Comment by chengchou** [comment]
Thanks @dtburk! It's a great solution.
