### ISSUE TITLE
Error in read_ipums_micro caused by read_long

### ISSUE THREAD

**Issue by chengchou** [mnpopcenter/ripums#62]
I got the following error from `read_ipums_micro`.

```
> # Read MTUS data labels
> ddi <- read_ipums_ddi("MTUS2/mtus_00002.xml")
> # Read MTUS data
> data <- read_ipums_micro(ddi)
Use of data from IPUMS MTUS is subject to conditions including that users
should cite the data appropriately. Use command `ipums_conditions()` for more
details.
Error in read_long(file, var_names, var_types, rt_info, var_pos_info,  : 
  Line is too short for rectype.
```

 I tried to debug by myself and found that error came from line 129--136 of file `micro_read.r`. 

```
 out <- hipread::hipread_long(
      data_file,
      col_spec,
      rt_info,
      progress = show_readr_progress(verbose),
      n_max = n_max,
      encoding = ddi$file_encoding
    )
```

I tried to find out what happened in `hipread_long`, but I think the function `read_long` inside `hipread_long` was written in C, with which I am unfamiliar.

Here is the link to the DDI and data file

```
https://www.dropbox.com/s/i98q0o6lx6j44s4/mtus_00002.xml?dl=0
https://www.dropbox.com/s/bifd59xp24zwfrl/mtus_00002.dat?dl=0
```

**Edit:**
I downloaded the `csv` version of the same data extraction, and `read_ipums_micro` can load the data. Reading the codes of `read_ipums_micro` (in particular, line 113--116), it worked because when the data are `csv`, it calls `readr::read_csv`.

**Comment by chriszs** [comment]
Had the same issue with 4.4 on my Mac using a notebook from someone for whom it apparently worked. They were using Linux, but no idea if that's the difference or if there's some other factor.

**Comment by gergness** [comment]
Hm, looks to me like the problem in how the DDI was made, it doesn't seem to match this file. 

Each line in the .dat text file is 113 characters long, but the ddi has:

```
...
    <var ID="HOURSWORKED" files="ExtractData" name="HOURSWORKED" intrvl="contin" dcml="0">
      <location StartPos="119" width="4" EndPos="122"/>
...
```

When loading subsets of variables it also doesn't seem to match. This could have happened if the files were renamed, or it also could indicate something bad happened in the extract system.

**Comment by chengchou** [comment]
Thanks @gergness!
I downloaded the `dat` data and DDI from IPUMS again. This time I can read the data. It might be my own problem.
