### ISSUE TITLE
Enhancement: IPUMS data download

### ISSUE THREAD

**Issue by edarin** [mnpopcenter/ripums#67]
Thanks a lot for developing this useful package.

Would it be possible to create a function for downloading data directly in R from the website?

Thanks!

**Comment by dtburk** [comment]
Thanks for the nudge @edarin! This functionality is planned, and we will be sure to update you on our progress here on this issue. In the meantime, there is some R sample code for interacting with the IPUMS API in R (though not using the ipumsr package) here: https://developer.ipums.org/docs/workflows/

**Comment by dtburk** [comment]
Closing this issue here, because I moved to ipums/ipumsr#12
